### ISSUE TITLE
user: Supplemental Page Design

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#101]
As a user I want to have access to an about, application, and survey page, so I can learn about the service, sign up and provide feedback.

## Definition of Done:
- [x] About page will be complete and styled with information about the service
- [ ] The application page will be accessible and ready to be sent to the backend for processing
- [ ] The survey page will be built and only accessible through direct link as it will not be accessible until the end of the semester

## Tasks:
- [x] Build about page html
- [x] Build about page style
- [x] Build about page TS
- [x] Build application page static (HTML, CSS)
- [x] Add dynamic content (slide show) for application questions
- [x] Find survey question from Dr. Carter
- [ ] Build survey page static
- [ ] Add dynamic content for questions
