### ISSUE TITLE
user: Home Page Design

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#17]
references #14 

As a User, I want to I want the homepage to be the first thing that appears when I navigate to the site, so that I can learn more about the service and how to sign-up.

## Definition of Done
- [ ] When I navigate to the site the homepage is the first page I see
- [ ] The homepage displays relevant information about the service, including features and benefits.
- [ ] Instructions for the sign-up process are prominently displayed on the homepage.

## Tasks
- [x] #81
- [x] Add the CSS for the hero section
- [x] #82 
- [x] Add styling to the hero section of the page
- [x] Add placeholder links for pages
- [x] Implement HTML structure for the card-like divs that sit below the hero
- [x] Add the CSS for the card section
- [x] Add hover effects to items on the page
