### ISSUE TITLE
user: Enhanced Survey Results Visualization for Instructors

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#19]
references #14

As an Instructor, I want to be able to view and further sort survey results with the ability to visualize them in multiple formats so that I can gain deeper insights into the feedback and make informed decisions to improve the program.

## Definition of Done
- [ ] Survey results are presented in various data visualization formats.
- [ ] Instructors can sort survey data based on different criteria.
- [ ] The system provides a user-friendly interface for effective survey result analysis.
## Tasks
- [ ] TBD
