### ISSUE TITLE
user: Session Details Page 

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#194]
As a User, I want to navigate to the Sessions Details page, so that I can gather details about my session.

references #28, #32, #14

## Definition of Done
- [x] Session details have a place to be properly displayed on the page.

## Tasks
- [x] Add the page fields.
- [x] Style page to be in uniform with the rest of the website.
- [x] Connect to the backend from the frontend

**Comment by xaviercaracter** [comment]
Resolved login issues and added base details page
[t : 60]

**Comment by xaviercaracter** [comment]
Merged session notes into this branch to make page uniform, waiting on backend endpoints to get info from the db through query string

**Comment by xaviercaracter** [comment]
Finished up with: page getting query string for the details and notes components, frontend components have been built.
[t :120]
