### ISSUE TITLE
user: End-of-Semester Report Upload for Instructors / tutor

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#20]
references #14

As an Instructor, I want to be able to upload end-of-semester reports for students, so that I can efficiently provide comprehensive feedback on their performance and progress.

## Definition of Done
- [x] Instructors can upload end-of-semester reports through the web app.
- [x] The system securely stores and associates uploaded reports with respective students.
- [x] Instructors receive confirmation of successful report uploads.

## Tasks
- [ ] TBD
