### ISSUE TITLE
user: Consistent Footer

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#209]
References #14 
As a User, I want a consistent footer, so I can navigate to more information.

## Definition of Done
- [x] Footer is persistent across all pages.
- [x] SDP branding and extra information is properly displayed.

## Tasks
- [x] Create footer component
- [x] Add SDP branding into the footer
- [x] Correct information pops up when hovering

**Comment by xaviercaracter** [comment]
Finished adding SDP logo and functionality
[t : 120]
