### ISSUE TITLE
user: End-of-Semester Survey Access for Users

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#21]
references #14

As a User, I want to be able to access an end-of-semester survey, so that I can provide valuable feedback on my experience and contribute to the improvement of the program.

## Definition of Done
- [ ] Users can access the end-of-semester survey through the web app.
- [ ] The survey is available for a specified period at the end of each semester.
- [ ] Users receive confirmation upon successful submission of the survey.

## Tasks
- [ ] TBD
