### ISSUE TITLE
user: Dashboard Page Design

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#22]
references #14 

As a User, I want to see widgets on my dashboard that link to various actions and views, so that I can navigate to different sections of the website

## Definition of Done
- [ ] The dashboard page layout is designed to accommodate multiple widgets.
- [ ] Each widget is linked to a specific action or view within the system.
- [ ] Widgets are clickable and lead the user to the intended action or view.

## Tasks
- [x] Add side menu to header to allow for navigation
- [x] Find and implement a usable library for calendar view, both in both modal and imbedded versions
- [x] Port project to no-standalone to allow for more seamless use of third party libraries
- [x] Build Session Widget with clickable events
- [x] Add announcement Widget
- [x] Style page to match home
