### ISSUE TITLE
user: PDF Download for Overall Semester Report for Users

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#23]
references #14

As a User, I want to be able to download a PDF of the overall semester report for my student, so that I can have a comprehensive and easily shareable document summarizing their academic performance.

## Definition of Done
- [ ] Users can initiate the download of a PDF document summarizing the overall semester report for their student.
- [ ] The PDF includes relevant details including comments and any additional information pertaining to the student's performance.
- [ ] The downloaded PDF is accessible and well-formatted.
## Tasks
- [ ] TBD
