### ISSUE TITLE
user: Profile Page Design

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#24]
references #14 

As a User, I want to access a dedicated profile page where I can manage preferences, update personal information, and view details related to specific students, so that I can tailor the tutoring experience to my specific needs.

## Definition of Done
- [x] The profile page includes sections for preferences, personal information, and student details.
- [x] Users can navigate between profile views to display different information or settings.

## Tasks
- [x] Make sidebar for nav within the profile page
- [x] Make and design layout for profile page
- [x] Make and design layout for children page
- [x] Implement navigation between views
- [x] Implement forms to allow users to update personal information

**Comment by ryesing** [comment]
[t:60]
Just other miscellaneous stuff, making sure that when we want to go ahead and start putting info in, their are templates and easily formattable things, so we don't have to redesign later
