### ISSUE TITLE
user: Linked Payment Page for Tutoring

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#26]
As a User, I want to have a link to the website to conveniently pay for tutoring using an embedded payment service, ensuring a seamless and secure transaction experience.

## Definition of Done
- [x] A payment link is implemented on the web app for tutoring session payments.

## Tasks
- [x] Acquire the link for payment
- [x] Research how to embed the link into the website
- [x] Create an experimental embedment
- [x] Test or present the embedment
- [x] Apply it to the service
