### ISSUE TITLE
user: Embedded Payment Service for Program Registration

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#27]
references #14

As a User, once accepted into the program, I want to be able to access an embedded payment service to complete my registration, ensuring a streamlined and secure process for joining the program.

## Definition of Done
- [ ] A dedicated page is provided to users within the web app.
- [ ] The page incorporates an embedded payment service for seamless and secure transaction processing.
- [ ] Users receives confirmation upon successful registration payment, and the system records the transaction details.

## Tasks
- [ ] TBD
