### ISSUE TITLE
user: Upcoming Sessions modal

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#28]
references #14 

As a User, I want to have access to a page where I can view upcoming tutoring sessions or events, so that I can plan my schedule effectively.

## Definition of Done
- [x] The page layout is designed to display upcoming tutoring sessions or events.
- [x] Users can navigate to the upcoming tutoring sessions page from the dashboard or navigation menu.
- [x] Each tutoring session or event is displayed with relevant details such as date, time, subject, and tutor.

## Tasks
- [x] Include a section on dashboard to include upcoming tutoring sessions
- [x] Build service to make secure calls to the DB to fill out widget
