### ISSUE TITLE
user: Visibility of Accepted and Pending Applicants for Instructors

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#29]
references #14

As an Instructor, I want to be able to view a clear list of individuals who have been accepted into the tutoring service, as well as those who are still pending acceptance, so that I can effectively manage and track the status of applicants.

## Definition of Done
- [ ] Instructors can access a dedicated page displaying a list of accepted applicants for the tutoring service.
- [ ] The page also includes a distinct section or indication for applicants whose status is still pending.
- [ ] The system provides relevant details for each applicant to facilitate informed decision-making.

## Tasks
- [ ] TBD
