### ISSUE TITLE
user: Consistent Header

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#31]
references #14 

As a User, I want a consistent header across the entire site, so that I can easily navigate between different sections of the website regardless of the page I'm on.

## Definition of Done
- [x] Design a header component with a hamburger menu to display additional navigation links and options.
- [x] Ensure that the header is consistent across all pages of the website.
- [x] The hamburger menu drops down when clicked
- [x] The links in the header correctly navigate around the website

## Tasks
- [x] Build header with items
- [x] Include dynamic hamburger menu
- [x] Design routes 
- [x] Complete CSS for header
