### ISSUE TITLE
user: Tutoring Notes and Comments Page

### ISSUE THREAD

**Issue by ryesing** [cs481-ekh/s24-illiterate-librarians#32]
references #14

As a User, I want to access a dedicated page where I can view tutoring notes and comments about specific sessions, so that I can review progress and insights shared during tutoring sessions.

## Definition of Done
- [x] Ensure that users can navigate to the tutoring notes page from the dashboard seamlessly.
- [x] Implement functionality to retrieve and display session-specific notes and comments dynamically.

## Tasks
- [x] Research Modals for Page/Modal decision
- [x] Create the component for the new page
- [x] Add link to the dashboard for the notes
- [x] Add modal/page to the dashboard
- [x] Add dummy data for testing
- [x] add endpoint to add session notes
- [x] add endpoint to get session notes

**Comment by xaviercaracter** [comment]
Researched proper practices to begin modal production 
[t : 120]

**Comment by xaviercaracter** [comment]
Component made
[t : 60]

**Comment by xaviercaracter** [comment]
Basic Skeleton of the Page made
[t: 120]

**Comment by xaviercaracter** [comment]
Basic Modal Completed
[t : 60 ]

**Comment by xaviercaracter** [comment]
About halfway done
[t : 120]

**Comment by xaviercaracter** [comment]
Refactored after unsuccessful testing
[t : 120]

**Comment by xaviercaracter** [comment]
Component complete, db connection still broken
[t : 75]
