### ISSUE TITLE
user: Account creation

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#37]
References #11 
As a user, I want to create an account with the website, so that I can be registered in the system to access materials

## Definition of Done
- [x] Users will have access to a page for account creation
- [ ] Users will have to fill out username, email, password and a password confirmation
- [ ] Users will have to submit valid information for the account to be created, valid username/password/email and the passwords must match
- [ ] Once users have filled out the account creation form and submitted their log in information will be saved in the database

## Tasks
- [x] #129
- [ ] Build account creation page with static and dynamic content
- [ ] Create and implement service to make account request from database
