### ISSUE TITLE
user: Automatic login after signup

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#38]
References #11 
As a user, I want to be automatically logged in after account creation, so that I can quickly begin accessing site resources

## Definition of Done
- [x] When the submit button on the account creation page is pressed and the login information is valid the user will be routed to their homepage

## Tasks
- [x] Completion of signup page
- [x] Addition of functionality

**Comment by xaviercaracter** [comment]
Performed research on appropriate methods to solve this problem.
[t : 70]

**Comment by xaviercaracter** [comment]
Worked with Drew D for the addition of the functionality
[t : 50]

**Comment by xaviercaracter** [comment]
Testing and further code modifications
[t: 120]

**Comment by xaviercaracter** [comment]
Failed tests, fixing...
[t: 80]

**Comment by xaviercaracter** [comment]
Testing successful
[t: 80]
