### ISSUE TITLE
user: Log in

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#42]
references #11 

As a User, I want to log in, so that I can utilize the tutoring service.

## Definition of Done
- [ ] When I click log in, I will be navigated to the log in page.
- [ ] When I am navigated to the log in page, I can sign in.
- [ ] When I sign in, I will be navigated to the homepage and be signed in.

## Tasks
- [ ] Redesign docker and endpoint to serve site
- [x] #119
- [ ] Build front end page to request auth token
- [ ] Restructure front end to require login for page access (reroute dashboard, profile and related pages)

**Comment by Connor-Thorpe01** [comment]
[t:120] added login functionality but ran into a issue with the backend connecting to database
