### ISSUE TITLE
user: Child Registration

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#43]
references #11 

As a User, when I first create my account, I want to add my child to my account, so that I can have them tutored.

## Definition of Done
- [ ] After I get navigated to the homepage, I will be prompted to add my children.
- [ ] When I navigate to the place where I add my children, I can fill in their information.
- [ ] When I finish filling out the information about my children, I want to click save.

## Tasks
- [ ] Add div with link to child registration to home page (will be hidden based on user status)
- [ ] Open modal when button is pressed with child information.
- [ ] Add option on dashboard to add an additional child
- [ ] Require additional application when new child is added
- [ ] Disable view entirely based on date
