### ISSUE TITLE
user: New Session log in

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#44]
references #11 

As a User, I want to log in for a new session after I have logged out, so that I can continue to utilize the service.

## Definition of Done
- [x] After signing out, I can navigate to the login page.
- [x] When I navigate to the log in page after logging out, I can sign back in.
- [x] After signing back in, I will be navigated to the homepage.

## Tasks
TBD
