### ISSUE TITLE
user: Preferred Method of Communication

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#45]
references #11 

As a User, I want to choose my preferred contact method, so that I can be received the tutoring notifications.

## Definition of Done
- [ ] I can navigate to the area where the communication method can be changed.
- [ ] I can change my preferred communication method.
- [ ] I can save my changes.

## Tasks
TBD
