### ISSUE TITLE
user: Log out

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#46]
references #11 

As a User, I want to log out of the website, so that I can secure my account when not in use.

## Definition of Done
- [x] When I click log out, I will be taken back to the homepage.
- [x] When I am back on to the homepage, I will no longer be signed in.

## Tasks
- [x] A log out button is on the header
- [x] When the button is pressed session and cookie is cleared
