### ISSUE TITLE
user: Password Recovery

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#47]
references #11 

As a User, I want to recover my password, so that I can log in to the website in case I forgot my password.

## Definition of Done
- [ ] When I click the forgot password link on the log in page, I will be taken to the password recovery page.
- [ ] When I am on the password recovery page, I can verify my identity with my account.
- [ ] When I verify my account, I can see my password to log in to the website.

## Tasks
TBD
