### ISSUE TITLE
user: Child Reg post Acct Creation

### ISSUE THREAD

**Issue by xaviercaracter** [cs481-ekh/s24-illiterate-librarians#48]
references #11 

As a User, I want to register children to my account after account creation, so that I can have them in tutoring as well.

## Definition of Done
- [x] After signing in I can navigate to where I can add more children to tutoring.
- [x] I can input my children's details for tutoring.
- [x] I can save the additions made to my list of children enrolled in tutoring.

## Tasks
- [ ] When account is created Dashboard prompts to create a child and take an application
- [ ] When button is pressed Child modal is opened

**Comment by AndrewDoering01** [comment]
Users can add children through profile page
