### ISSUE TITLE
user: Email Confirmation

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#49]
As a User, I want to receive an email after account creation, so that I can confirm my account to verify my identity

## Definition of Done
- [ ] When a user creates an account a formatted email is sent with a custom link to verify the email
- [ ] When an account is created the 'confirmed' field in the database will be default to false
- [ ] The user will be able to click a link on the received email to confirm their account after another log
- [ ]The database will update the 'confirmed' field for the user once they've logged in again and their account is confirmed.

## Tasks
- [ ] Task 1
- [ ] Task 2
