### ISSUE TITLE
user: Initial child creation

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#50]
As a user, I want to be prompted to add a student under my account upon initial login, so that I can apply for the tutoring semester as fast as possible

## Definition of Done
- [ ] Upon initial login a user will be prompted to add a child to their dashboard
- [ ] After accepting the prompt the user be served a modal to fill out details pertaining to their child
- [ ] These details will contain age, name, subject and grade level
- [ ] Once the user confirms child creation, the child will be added to the database under that specific user
- [ ] Once the child has been created the pre-semester survey will be available to the parent

## Tasks
- [ ] Task 1
- [ ] Task 2
