### ISSUE TITLE
user: Admin/Instructor User Mangement

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#51]
References: #11 
As an Admin or Instructor, I want to be able to upgrade users to tutors, so that I can manage them separtely

## Definition of Done
- [x] Admins and instructor will have a user management tab under their dashboard
- [x] Instructors will be able to search by name or username and manage a certain account
- [x] Instructors will be able to check an "is tutor" field
- [x] The status of that user will be moved from standard user to tutor in the DB

## Tasks
- [x] #177
- [x] #198
- [x] #213
- [x] Create route guard for admin dash on frontend
- [x] #219
- [x] #225
