### ISSUE TITLE
user: Client Schedule View

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#53]
References #12 
As a user, I want to view my schedule, so that I can efficiently manage my time
## Definition of Done
- [x] Under the user dashboard they will see the weeks schedule with all events listed
- [x] Once accepted for tutoring the scheduled will automatically fill in all semester tutoring dates
- [x] When clicked on the calendar modal will expand showing the month, user will be able to browse to different months using on screen arrows
- [x] The calendar is dynamic, new events can be added or removed by the instructor if necessary

## Tasks
- [x] Add month calendar to full calendar
- [x] Add http service to get user's events
- [x] #139

**Comment by AndrewDoering01** [comment]
Calendar and dynamic calendar were added for dashboard design
