### ISSUE TITLE
user: Client Tutoring Application/Survey

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#54]
References #12 
As a Client, I want to be able to take a pre-term survey , so that I can apply for tutoring

## Definition of Done
- [x] Once a child is created a survey button will be available for that child
- [x] When the survey is selected a modal will open and the potential client will be able to take the survey
- [x] Once completed the client will submit the survey for review by the instructor

## Tasks
- [x] Create a modal for a user to fill out the application for a specific child
- [x] Add HTTP handler to to send request for application
- [x] #145
- [x] #144
- [x] #151
- [x] #146

**Comment by AndrewDoering01** [comment]
[t:60]

Added ability for children to automatically check for survey state
