### ISSUE TITLE
user: Client Session Cancellation

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#55]
References: #12 
As a client, I want to be able to a cancel tutoring session, so that I can inform my tutor and the instructor that I will be missing a day ahead of time

## Definition of Done
- [ ] When a tutoring session is selected under the schedule there will be an option to cancel session if it hasn't already passed
- [ ] When the cancel session button a pressed a confirmation will appear on the screen with a check box and submit button to confirm the cancellation
- [ ] Once the cancellation is confirmed the instructor and the client's tutor will informed of the cancellation
- [ ] The session will be removed from the clients dashboard once cancelled
- [ ] If the client cancels more than 3 session during a term they will be warned that further cancellation may result in not being accepted back during future semesters.

## Tasks
TBD
