### ISSUE TITLE
user: Initialize project

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#57]
As a developer, I want to initialize the project so that we can begin work

## Definition of Done
- [x] Backend dir done and has all needed folders and files
- [x] Front end dir done and has all needed folders and files
- [x] git ignore added
- [x] docker and docker-compose files

## Tasks
- [x] init backend dir
- [x] init front end dir
- [x] add files
