### ISSUE TITLE
user: Client Notification Setting

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#58]
References #12 
As a client, I want to enable or disable, so that I can choose if I receive live updates

## Definition of Done
- [ ] Under user profile they will have a setting to enable or disable notifications 
- [ ] Clients will be served a confirmation modal when the setting is adjusted and saved
- [ ] The database will be updated the the clients preference 

## Tasks 
- [x] #159 
- [ ] #160

Completed the below task in #148 
- [x] #176

**Comment by AndrewDoering01** [comment]
[t:90]
Completed functionality
