### ISSUE TITLE
user: SMS Notifications

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#59]
References #12 
As a user, I want to be able to receive notifications via SMS, so that I can have live updates about the service

## Definition of Done
- [ ] Users will be able to receive messages if enabled via their provided phone number
- [ ] Twilio will receive and distribute the message to users

## Tasks
- [ ] create an endpoint that will allow an instructor to send text messages in mass to all people enrolled
- [ ] allows for only specific groups to get text messages

**Comment by Connor-Thorpe01** [comment]
[t:60] researching tiwlio and set up trial account

**Comment by Connor-Thorpe01** [comment]
[t:60] researching API and started messing with sending messages

**Comment by Connor-Thorpe01** [comment]
[t: 60] hit a roadblock. cannot be sent to nonvirtual numbers without verification.

**Comment by Connor-Thorpe01** [comment]
[t: 60] rewrote dao to get guardian 2 phone as well and only get users who put there contact method as Text or Both
