### ISSUE TITLE
user: Instructor Mass Message Creation

### ISSUE THREAD

**Issue by AndrewDoering01** [cs481-ekh/s24-illiterate-librarians#62]
References #12 
As an Instructor, I want to be able to create mass or direct messages to users , so that I can keep them updated about events

## Definition of Done
- [ ] Under the instructor dashboard they will be able to create a new message
- [ ] When new message is selected they will be able to select a specific user or all accepted users
- [ ] There will be a field to draft the message and a button to sent
- [ ] They will be asked for confirmation before sending
- [ ] The instructor can choose how often or when the message is sent or set reminders about specific events
- [ ] The message will be handled by Twilio and sent to all registered phone numbers
- [ ] Instructors will be able access a view delete scheduled messages

## Tasks
TBD
