### ISSUE TITLE
user: Create Database schema

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#63]
As a Developer, I want to create a MySQL schema and diagram, so that I can store and use information

## Definition of Done
- [x] Diagram for database is created
- [x] MySql schema is created with constraints 

## Tasks
- [x] #65
- [x] #66
- [x] Walk through some example situations of data being passed with most, if not the whole team to ensure that the schema is functioning as desired.
