### ISSUE TITLE
Stub out Build Test and CI github actions

### ISSUE THREAD

**Issue by ALackey-ai** [cs481-ekh/s24-illiterate-librarians#72]
As a Developer, I want to create the basic github actions, so that other developers can merge pull requests into the repo and have the project be automatically built and tested.

## Definition of Done
- [x] Stub out a build.sh file
- [x] Stub out a test.sh file
- [x] Setup the github actions on pull request merges
- [x] Create the status badges

## Tasks
- [x] #73
- [x] #74
- [x] #75
