### ISSUE TITLE
user: add JWT to project

### ISSUE THREAD

**Issue by Connor-Thorpe01** [cs481-ekh/s24-illiterate-librarians#95]
As a Developer, I want to add JSON Web Tokens, so that I can send encrypted messages from between the frontend and backend to keep user information secure.

## Definition of Done
- [ ] Auth package made in the backend
- [ ] add it to Gin middleware
- [ ] Can create and use tokens

## Tasks
- [ ] Create own middleware for JWt and Add it to Gin middleware
- [ ] Test JTW middleware
